### ISSUE TITLE
Zip-Export does not run inMantis 2.x

### ISSUE THREAD

**Issue by ghost** [mantisbt-plugins/ZipExport#1]
We like to have this plugin available for version 2.x

**Comment by dregad** [comment]
@CasN I saw you just created a new repo for 2.x compatibility https://github.com/mantisbt-plugins/ZipExport2

I believe it would be better if I give you access to this repo, and you become its new maintainer. This way we keep a single plugin for this functionality.

What do you think ?

**Comment by ghost** [comment]
That would also be fine Damien. I tried to get write right but no response from the original maintainer.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dregad** [comment]
OK, I'll make the necessary adjustments to give you access to it.

For another time, if it's a plugin existing in the *mantisbt-plugins* organization and you get no response from the author, you can ping me or @mantisbt-plugins/core-team to request access. That's one of the reasons we created this org, to facilitate takeover of unmaintained plugins.

**Comment by dregad** [comment]
I added you to the plugin's support team, which should give you push access to the repository. Let me know if there's something that your need to do but are unable to with these rights, or if you need any help.

If you want to change the structure (i.e. move the plugin's code to the root), feel free to do so.

Please delete the ZipExport2 repository when you're done migrating the code here.

**Comment by ghost** [comment]
Compatability for Mantis verion 2.x can be found in branch Mantis2

**Comment by dregad** [comment]
Have a look at https://github.com/mantisbt-plugins/ZipExport/tree/2x branch and the [note I just posted on Gitter](https://matrix.to/#/!DvgPTBxArafnQrXodD:gitter.im/$qI1KwjEh1wOTgc9zHe3jkRkFMClEV1C4RKytS2DlOD8?via=gitter.im&via=matrix.org)

You'll probably want to remove Robert's e-mail from the plugin's contact and just keep yours; and the URL is invalid.
